service: alexa-astronomie-skill

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 128

package:
  individually: true
  exclude:
    - '**'

functions:
  flash-briefing:
    handler: dist/flash-briefing.handler
    package:
      include:
        - dist/flash-briefing*
    events:
      - http:
          path: today
          method: get
          integration: LAMBDA
